### ISSUE TITLE
[需求] 后端开源

### ISSUE THREAD

**Issue by alan-x** [lzuntalented/lz-h5-edit#12]
请求后端开源

**Comment by lzuntalented** [comment]
后端没有太多东西，就是落库和查询操作
等我把前后端的一键化部署搞好再开源吧

**Comment by xiaolu11bnb** [comment]
后端的数据表能先看一下吗？

**Comment by lzuntalented** [comment]
> 后端的数据表能先看一下吗？

CREATE TABLE `l_opus` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(256) NOT NULL,
  `content` text NOT NULL,
  `add_time` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `user_id` int(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=648 DEFAULT CHARSET=utf8

就这个一个表，编辑器产生的内容，存在content字段上

**Comment by zsz91** [comment]
谢谢分享

**Comment by lzuntalented** [comment]
后端已开源，对应目录packages/server
