### ISSUE TITLE
高度未充满屏幕

### ISSUE THREAD

**Issue by moshanghan** [lzuntalented/lz-h5-edit#17]
看了下demo，页面高度没有撑满屏幕，
这算bug吗？

**Comment by lzuntalented** [comment]
能具体描述下是哪个页面吗
我来检查下

**Comment by moshanghan** [comment]
![image](https://user-images.githubusercontent.com/30591457/82831131-29db5f80-9eea-11ea-8cb3-0cf83d818275.png)

是设计如此吗？

**Comment by moshanghan** [comment]
这个问题的来源是这样的，
每个手机型号的屏幕宽高比例不通，无法完全兼顾，已宽度为主要好于已高度为主，这样就放弃了高度，当显示的时候，高度就会遇到撑不满或者溢出的问题

**Comment by lzuntalented** [comment]
是这样设计的，编辑尺寸是320*480，为适配多种尺寸手机，以宽度满屏，高度居中，
至于不充满的情况，可以加个符合主题的背景图进行融色，展示效果就会好很多了
