### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by waysun** [lzuntalented/lz-h5-edit#19]
ERROR in ./packages/client/src/pages/create/index.js
Module not found: Error: Can't resolve '@lzshow/design' in 'D:\avatar_project\lz-h5-edit\packages\client\src\pages\create'
 @ ./packages/client/src/pages/create/index.js 5:0-38 111:42-50
 @ ./packages/client/src/pages/create/Loadable.js
 @ ./packages/client/src/router/index.js
 @ ./packages/client/src/index.js

**Comment by lzuntalented** [comment]
看着像是没构建好，按照使用说明在build一次试试
