### ISSUE TITLE
很不错的项目，如果数据要落库，有什么好一点的方案和建议吗？

### ISSUE THREAD

**Issue by crixusshen** [lzuntalented/lz-h5-edit#2]
很不错的项目，如果数据要落库，有什么好一点的方案和建议吗？

**Comment by lzuntalented** [comment]
针对编辑器的数据落库主要针对两点：
1.可再编辑场景
2.可访问作品
要做到这两点只需要把发布时，编辑器的store数据序列化到数据库就行
具体实现可参考`src\pages\create\components\Header\header.js` 80行的onPublish方法
