### ISSUE TITLE
想加入，提供java版本server

### ISSUE THREAD

**Issue by waysun** [lzuntalented/lz-h5-edit#20]
希望加入一起做，提供Java版本后台
微信:waysun1983
yyk1504@163.com

**Comment by lzuntalented** [comment]
你可以新建一个仓库来构建java版本的后台，参考下当前项目的node后端server目录下，有想法可以在qq群里@我

**Comment by waysun** [comment]
OK


| |


|
|
yyk1504@163.com
|
签名由网易邮箱大师定制
在2020年12月10日 21:28，可我不爱聪明<notifications@github.com> 写道：

你可以新建一个仓库来构建java版本的后台，参考下当前项目的node后端server目录下，有想法可以在qq群里@我
