### ISSUE TITLE
npm构建时候报错

### ISSUE THREAD

**Issue by hiyuey3** [lzuntalented/lz-h5-edit#21]
npm i lerna -g
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this
以上是报错内容，我如何处理它

**Comment by lzuntalented** [comment]
这个是警告可以不用关注，因为lerna依赖了request包，而request已经被宣告deprecated，静待lerna修复吧

**Comment by hiyuey3** [comment]
十分感谢
